module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/GoXKLVfFI?mode=gi_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://raw.githubusercontent.com/xhclintohn/Music-Clips-Collection/main/mini.png',
    NEWSLETTER_JID: '120363322461279856@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝐭𝐨𝐱𝐢𝐜-𝐦𝐢𝐧𝐢-𝐛𝐨𝐭',
    OWNER_NAME: '𝐱𝐡_𝐜𝐥𝐢𝐧𝐭𝐨𝐧',
    OWNER_NUMBER: '254735342808',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> 𝐩𝐨𝐰𝐞𝐫𝐞𝐝 𝐛𝐲 𝐱𝐡_𝐜𝐥𝐢𝐧𝐭𝐨𝐧',
    CHANNEL_LINK: 'https://whatsapp.com/channel/p',
};
