const axios = require('axios');

module.exports = {
    name: 'lyrics',
    async execute(socket, msg, number, userConfig, loadUserConfigFromMongo) {
        const text = msg.message?.conversation || msg.message?.extendedTextMessage?.text || "";
        const args = text.trim().split(/\s+/);
        const query = args.slice(1).join(' ');

        const fakevcard = {
            key: { remoteJid: "status@broadcast", participant: "0@s.whatsapp.net", fromMe: false, id: "TOXIC_LYRICS_ID" },
            message: { contactMessage: { displayName: "Toxic-Mini-Bot", vcard: `BEGIN:VCARD\nVERSION:3.0\nN:Toxic;;;;\nFN:Toxic-Mini-Bot\nTEL;type=CELL;type=VOICE;waid=254735342808:+254 735 342 808\nEND:VCARD` } }
        };

        if (!query) {
            return socket.sendMessage(msg.key.remoteJid, { 
                text: "Are you mute? Give me a song title so I can find the lyrics you'll probably mispronounce anyway." 
            }, { quoted: fakevcard });
        }

        try {
            await socket.sendMessage(msg.key.remoteJid, { react: { text: '⌛', key: msg.key } });

            const { data } = await axios.get(`https://api.deline.web.id/tools/lyrics`, {
                params: { title: query }
            });

            if (!data.status || !data.result || data.result.length === 0) {
                await socket.sendMessage(msg.key.remoteJid, { react: { text: '❌', key: msg.key } });
                return socket.sendMessage(msg.key.remoteJid, { 
                    text: `I couldn't find any lyrics for "${query}". Either the song is trash or your spelling is.` 
                }, { quoted: fakevcard });
            }

            // Grabbing only the first result as requested
            const song = data.result[0];
            const sanitized = (number || '').replace(/[^0-9]/g, '');
            const cfg = await loadUserConfigFromMongo(sanitized) || {};
            const botName = cfg.botName || 'Toxic-Mini-Bot';

            const lyricText = `*『 𝙻𝚈𝚁𝙸𝙲𝚂 𝙵𝙸𝙽𝙳𝙴𝚁 』*

╭───(    \`𝚂𝚘𝚗𝚐 𝙳𝚎𝚝𝚊𝚒𝚕𝚜\`    )───
> ───≫ 🎵 𝚃𝚒𝚝𝚕𝚎 : ${song.name}
> ───≫ 👤 𝙰𝚛𝚝𝚒𝚜𝚝 : ${song.artistName}
> ───≫ 💿 𝙰𝚕𝚋𝚞𝚖 : ${song.albumName || 'N/A'}
╰──────────────────☉

${song.plainLyrics}

*Generated by ${botName}*`;

            await socket.sendMessage(msg.key.remoteJid, { react: { text: '✅', key: msg.key } });

            await socket.sendMessage(msg.key.remoteJid, {
                text: lyricText,
                contextInfo: {
                    externalAdReply: {
                        title: `Lyrics: ${song.name}`,
                        body: `Artist: ${song.artistName}`,
                        thumbnailUrl: cfg.logo || 'https://raw.githubusercontent.com/xhclintohn/Music-Clips-Collection/main/mini.png',
                        sourceUrl: "https://xhclinton.com/minibot",
                        mediaType: 1,
                        renderLargerThumbnail: false
                    }
                }
            }, { quoted: msg });

        } catch (error) {
            await socket.sendMessage(msg.key.remoteJid, { react: { text: '❌', key: msg.key } });
            await socket.sendMessage(msg.key.remoteJid, { 
                text: "Lyrics search crashed harder than your singing career. Try again later." 
            }, { quoted: fakevcard });
        }
    }
};
